---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: check if already good
    shell:
      sysctl net.ipv4.ip_forward
    register: output

  - name: exit gracefully if already done
    meta: end_host
    when: "'net.ipv4.ip_forward = 1' | string in output.stdout"

  - name: run script
    script:
      cmd: shell/enable-i-pv4-packet-forwarding.sh

  - name: check if it worked
    shell:
      sysctl net.ipv4.ip_forward
    register: output

  - name: fail if it didnt work
    fail:
      msg: "no success"
    when: "'net.ipv4.ip_forward = 1' | string not in output.stdout"
