---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: init control plane
      shell:
        kubeadm init --cri-socket unix:///var/run/containerd/containerd.sock --pod-network-cidr=192.168.0.0/16 --control-plane-endpoint=10.0.1.3

    # - name: install flannel for container networking
    #   shell:
    #     KUBECONFIG=/etc/kubernetes/admin.conf  kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml --validate=false

    - name: get join command
      shell:
        kubeadm token create --print-join-command
      register: output

    - name: Remove the join file
      become: no
      file:
        path: ./shell/join.sh
        state: absent
      delegate_to: localhost

    - name: save join command to local file
      become: no
      lineinfile:
        path: ./shell/join.sh
        line: |
          {{ output.stdout }} --cri-socket unix:///var/run/containerd/containerd.sock
        create: true
      delegate_to: localhost
